// Fake content for the blog UI kit. window.BLOG_DATA
window.BLOG_DATA = {
  author: {
    handle: '@staff',
    role: 'Staff Engineer',
    bio: 'I write about distributed systems, the BEAM, and building LLM agents that survive contact with production.',
    location: 'remote / utc+0',
    links: [
      { label: 'github', href: '#' },
      { label: 'rss', href: '#' },
      { label: 'mastodon', href: '#' },
    ],
  },
  tags: [
    { name: 'elixir', count: 14 },
    { name: 'dist-sys', count: 11 },
    { name: 'llm', count: 9 },
    { name: 'agents', count: 7 },
    { name: 'otp', count: 6 },
    { name: 'perf', count: 5 },
    { name: 'evals', count: 4 },
  ],
  posts: [
    {
      id: 'supervision-trees-lie',
      n: '01',
      title: 'Supervision trees are a lie you tell yourself',
      date: '2026 · 05 · 12',
      iso: '2026-05-12',
      read: '14 min',
      tags: ['elixir', 'otp'],
      featured: true,
      excerpt: 'What "let it crash" actually costs once you have 40k processes and a partitioned cluster — and why the answer is rarely a bigger supervisor.',
      body: [
        { t: 'p', c: 'Every Elixir talk eventually reaches the slide with the supervision tree. Boxes, arrows, a reassuring story: a process dies, its supervisor restarts it, the system heals. It is a genuinely good model. It is also, at scale, a comfortable lie.' },
        { t: 'h2', c: 'The cost nobody graphs' },
        { t: 'p', c: 'Restarts are not free. A restart discards in-memory state, and at 40k processes the question is no longer "did it restart" but "what did the restart take with it". When a partition heals and ten thousand GenServers restart in the same second, you do not have resilience. You have a thundering herd with extra steps.' },
        { t: 'code', filename: 'lib/cluster/partition.ex', language: 'elixir', highlight: [4], c: 'defmodule Cluster.Partition do\n  def handle_heal(replicas) do\n    replicas\n    |> Enum.map(&reconcile/1)   # <- this is the herd\n    |> Enum.reduce(%{}, &merge/2)\n  end\nend' },
        { t: 'callout', tone: 'warning', c: 'A supervisor restarting 10k children is not a recovery strategy. It is a denial-of-service you scheduled against yourself.' },
        { t: 'h2', c: 'What actually helps' },
        { t: 'p', c: 'Backpressure at the boundary, jittered restart intervals, and treating reconciliation as a first-class operation instead of an accident of restart order. The supervision tree is the floor, not the strategy.' },
        { t: 'callout', tone: 'tip', c: 'Reach for recon before :observer when a node is already hot — :observer will happily make a bad day worse.' },
        { t: 'p', c: 'None of this means "let it crash" is wrong. It means the slogan ends a sentence that production makes you finish.' },
      ],
    },
    {
      id: 'agentic-harness',
      n: '02',
      title: "Building an agentic harness that doesn't lie",
      date: '2026 · 04 · 28',
      iso: '2026-04-28',
      read: '22 min',
      tags: ['llm', 'agents'],
      excerpt: 'Tool-call verification, replayable transcripts, and why your eval loop is the actual product — not the model.',
    },
    {
      id: 'crdts',
      n: '03',
      title: 'CRDTs I have known and loved',
      date: '2026 · 04 · 09',
      iso: '2026-04-09',
      read: '9 min',
      tags: ['dist-sys'],
      excerpt: 'A field guide to merge semantics that survive contact with real network partitions, ranked by how much they have hurt me.',
    },
    {
      id: 'profiling-beam',
      n: '04',
      title: 'Profiling the BEAM without losing your mind',
      date: '2026 · 03 · 30',
      iso: '2026-03-30',
      read: '11 min',
      tags: ['elixir', 'perf'],
      excerpt: 'recon, :observer, and the flamegraph workflow I actually reach for when a node is on fire at 3am.',
    },
    {
      id: 'eval-loop-product',
      n: '05',
      title: 'The eval loop is the product',
      date: '2026 · 03 · 15',
      iso: '2026-03-15',
      read: '18 min',
      tags: ['llm', 'evals'],
      excerpt: 'Stop shipping prompts. Start shipping the harness that tells you, ruthlessly and automatically, when a prompt got worse.',
    },
    {
      id: 'genserver-myths',
      n: '06',
      title: 'Six things I believed about GenServer that were wrong',
      date: '2026 · 02 · 26',
      iso: '2026-02-26',
      read: '7 min',
      tags: ['elixir', 'otp'],
      excerpt: 'A short, slightly embarrassing list — collected over eight years and roughly four production incidents.',
    },
  ],
};
